name: PR Checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-and-lint:
    name: Check & Lint
    runs-on: macos-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Bun (JavaScript package manager)
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Step 2.5: Cache Bun dependencies
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Step 3: Setup Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Step 3.5: Cache Rust dependencies
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: bun install

      # Step 5: Sync SvelteKit (generates .svelte-kit/tsconfig.json)
      - name: Sync SvelteKit
        run: bunx svelte-kit sync

      # Step 6: Run tests
      - name: Run tests
        run: make test

      # Step 7: Run check (type checking)
      - name: Run check
        run: make check

      # Step 8: Run lint (linters)
      - name: Run lint
        run: make lint
